### ISSUE TITLE
Donations endpoint on the checkout api

### ISSUE THREAD

**Issue by sam899** [Adyen/adyen-ruby-api-library#118]
**ruby version**: 2.7.6
**Library version**: 6.2.0

**Describe the solution you'd like**
Is it possible to support the donations endpoint on the checkout api?
https://docs.adyen.com/api-explorer/Checkout/68/post/donations

**Comment by jillingk** [comment]
Hi @sam899,

Thanks a lot for reaching out to us. We have been very busy automating the other libraries, hence we're running a bit behind on some of the endpoint on this library. However I've just opened a PR #120  to address the missing Checkout endpoints here! Also stay tuned because we're now going to start working more on getting this library up to speed as well.

Best, Jilling
Adyen

**Comment by sam899** [comment]
Great thank you @jillingk
