### ISSUE TITLE
How to get errors raised?

### ISSUE THREAD

**Issue by awendt** [Adyen/adyen-ruby-api-library#21]
Hi,

we're migrating from another library to this one. We'd like errors to be raised by Faraday so we can handle them properly. Faraday even provides a ready-to-use middleware, [`Faraday::Response::RaiseError`](https://github.com/lostisland/faraday/blob/master/lib/faraday/response/raise_error.rb).

However, this library does not support modifying the middleware stack. Is there anything I can do to work around that limitation? Or does this require a change in the library?

Thanks!

**Comment by crrood** [comment]
Hi Awent,

Thanks for the feedback.

As Adyen's API only returns a subset of the available HTTP errors, the library maps those errors to their specific meanings within the Adyen API instead of their generic definitions.  We believe that this provides more value, and is in line with the philosophy of the library in general.

If you want to branch the library locally and use the Faraday middleware instead that is of course possible as well.

Best,
Colin

**Comment by awendt** [comment]
We are now wrapping the response and raise errors as we see fit. I'll close this.
